### PR TITLE
Partial resolution of NASA-PDS/devops#5 (Java side)

### PR DESCRIPTION
**Pull request by nutjob4life**
## 📜 Summary

Merge this if you dare to help with the Java side of NASA-PDS/devops#5 by adding some additional documentation and visibility to the importance of setting up teams on new repositories.

## 🩺 Test Data and/or Report

```console
$ mvn test
[INFO] Scanning for projects...
…
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
…
$ echo \U+1F389
🎉
``` 

## 🧩 Related Issues

- NASA-PDS/devops#5

### CODE REVIEW

**Review by MJJoyce — APPROVED** [review]
:+1:

**Comment by jordanpadams** [comment]
@MJJoyce per similar comments to @nutjob4life for these PRs, if you are confident they are good to go, feel free to approve and merge as well. Otherwise it will get stuck open until someone else has to come back and merge it. If you'd like a second opinion from @tloubrieu-jpl , @jimmie or me, that is totally fine too, just tag us so we can make sure to prioritize it

**Comment by MJJoyce** [comment]
Sounds good @jordanpadams. Didn't want to step on any toes by circumventing some process. I'll merge from now on if stuff looks good or I'll explicitly give people a poke.

**Comment by nutjob4life** [comment]
This is indeed most wootly.

**Comment by jordanpadams** [comment]
@MJJoyce no problem. The process is still being worked out, so comments welcome.

**Pull request merged**
